version: '3.7'
services:
  api:
    working_dir: /app
    build: ./packages/back/api
    ports:
      - 8000:8000
    command: yarn start
    volumes:
      - ./packages/back/api:/app

  front:
    build: ./packages/front
    working_dir: /front
    command: make front-startup
    ports:
      - 8080:8080
    volumes:
      - ./packages/front:/front
