version: '3.7'

services:

  front:
    build: ./packages/front
    working_dir: /front
    command: make front-startup
    ports:
      - 8080:8080
    volumes:
      - ./packages/front:/front
    depends_on:
      - api

  api:
    working_dir: /api
    build: ./packages/back/api
    ports:
      - 8000:8000
      - 9229:9229
    command: yarn start
    volumes:
      - ./packages/back/api:/api
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=${POSTGRES_USER}   
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}   
    - POSTGRES_DB=${POSTGRES_DB}