version: '3.7'

services:

  api:
    container_name: api
    image: node:20 
    working_dir: /app
    command: make api-startup
    ports:
      - 8000:8000
    env_file: .env.test
    environment:
      - TEST_ENV=true
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env.test