version: '3.7'

services:

  front:
    container_name: front
    image: node:16 
    working_dir: /front
    command: make front-startup
    ports:
      - 8080:8080
    volumes:
      - .:/front
    depends_on:
      - api

  api:
    container_name: api
    image: node:16 
    working_dir: /app
    command: make api-startup
    ports:
      - 8000:8000
      - 9229:9229
    environment:
      - DATABASE_URL=postgres://ppoker:123456@db:5432/ppoker
      - DEBUG="*"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}   
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}   
      - POSTGRES_DB=${POSTGRES_DB}