name: On Pull Request

on: pull_request

jobs:
  build:
    name: Build projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build api
        run: cd packages/api && yarn build

      - name: Build front-end
        run: cd packages/front && yarn build

      - name: Build store
        run: cd packages/store && yarn build

  unit-tests-store:
    name: Run store unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: source .env.test && cd packages/store && yarn test
